Repository Codin-Nerds/Neutron-Bot, pull requests merged in 2020-10, with the labels that each got.

#10 Add owner-focused commands
  bot/__main__.py
  bot/cogs/sudo.py
  bot/config.py
  bot/core/bot.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#13 Add channel locking feature
  CONTRIBUTING.md
  Pipfile
  Pipfile.lock
  bot/__main__.py
  bot/cogs/moderation/__init__.py
  bot/cogs/moderation/lock.py
  bot/core/converters.py
  bot/core/timer.py
  bot/database/__init__.py
  bot/database/roles.py
  bot/utils/time.py
Labels: priority: 1 - high, status: needs review, type: feature

#14 Introduce caching to the database and improve table population
  CONTRIBUTING.md
  bot/core/timer.py
  bot/database/__init__.py
  bot/database/log_channels.py
  bot/database/roles.py
Labels: priority: 1 - high, status: WIP, type: feature

#16 Add setup commands
  CONTRIBUTING.md
  bot/__main__.py
  bot/cogs/moderation/lock.py
  bot/cogs/setup/__init__.py
  bot/cogs/setup/permissions.py
  bot/cogs/setup/roles.py
  bot/core/converters.py
  bot/database/__init__.py
  bot/database/log_channels.py
  bot/database/permissions.py
  bot/database/roles.py
  bot/utils/time.py
Labels: priority: 1 - high, status: needs review, type: feature

#15 Add Embed Handler
  bot/__main__.py
  bot/cogs/embeds.py
Labels: priority: 2 - normal, status: needs review, type: feature

#17 Add error handler
  bot/__main__.py
  bot/cogs/embeds.py
  bot/cogs/error_handler.py
  bot/cogs/sudo.py
Labels: priority: 0 - critical, status: needs review, type: feature
